version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - '3000:3000'
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-app
    ports:
      - '3001:80'
    depends_on:
      - backend